### ISSUE TITLE
Error: command failed

### ISSUE THREAD

**Issue by peterwin97** [RMCob/homebridge-wyze-robovac#1]
**Describe The Bug:**
Just getting it set up and I am running into this error:

> [WyzeRoboVac] error: Command failed: python3 /usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumRoomList.py [myemail] [mypassword] Home Vacuum
USAGE: /usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumRoomList.py wyze_email wyze_password robovac_nickname

**To Reproduce:**
Enter credentials for Wyze and restart HomeBridge.

**Expected behavior:**
Automatically load Wyze devices into HomeBridge

**Logs:**

> [WyzeRoboVac] error: Command failed: python3 /usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumRoomList.py [myemail] [mypassword] Home Vacuum
USAGE: /usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumRoomList.py wyze_email wyze_password robovac_nickname

**Plugin Config:**

> {
>             "name": "WyzeRoboVac",
>             "username": "myemail",
>             "password": "my password",
>             "statusCheckRefreshInterval": 30,
>             "idleBatteryCheckRefreshInterval": 1800,
>             "busyBatteryCheckRefreshInterval": 120,
>             "path2py_stubs": "/usr/lib/node_modules/homebridge-wyze-robovac/py_helpers",
>             "debugLevel": 0,
>             "platform": "WyzeRoboVac"
>         }

**Environment:**

* **Plugin Version**: 1.2.1
* **Homebridge Version**: 1.4.0
* **Node.js Version**: v16.14.2
* **NPM Version**: v8.5.0
* **Operating System**: Ubuntu

**Comment by RMCob** [comment]
@peterwin97  I think the problem may be that your vacuum name has a blank in it. Could you change the name in the Wyze app to remove the blank (Use a "_" perhaps) and then try it again and report back. Thanks....

**Comment by peterwin97** [comment]
That fixed it, thanks!
