### ISSUE TITLE
getVacuumDeviceList.py no such file or directory

### ISSUE THREAD

**Issue by bobziroll** [RMCob/homebridge-wyze-robovac#10]
**Describe Your Problem:**

Just trying to get things to work at all. When I enter the Homebridge terminal, there's not even a `node_modules` folder in the `/usr/lib` directory, so I'm assuming I've missed some setup step maybe?

**Logs:**

```
[WyzeRoboVac] error: Command failed: python3 /usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py ***********@gmail.com *********
python3: can't open file '/usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py': [Errno 2] No such file or directory
```

**Plugin Config:**
I suspect it has to do with the `path2py_stubs` path since it's not able to find it.
```json
{
    "name": "WyzeRoboVac",
    "username": "***********@gmail.com",
    "password": "**********",
    "statusCheckRefreshInterval": 30,
    "idleBatteryCheckRefreshInterval": 1800,
    "busyBatteryCheckRefreshInterval": 120,
    "path2py_stubs": "/usr/lib/node_modules/homebridge-wyze-robovac/py_helpers",
    "debugLevel": 0,
    "platform": "WyzeRoboVac",
    "_bridge": {
        "username": "***",
        "port": 45277
    }
}
```

**Screenshots:**

**Environment:**
Not sure what this means, sorry 😕

* **Plugin Version**: 1.2.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.16.0
* **NPM Version**: 8.11.0
* **Operating System**: Synology DSM 7

**Comment by RMCob** [comment]
@bobziroll I'm sorry but I cannot help you. You are running Homebridge on your Synology system, which I do not have. The plugin was developed on Debian Linux running on a Raspberry Pi. I have no idea where things are stored on Synology. Perhaps someone who is running Homebridge on Synology can help. Once you discover where the py__helpers directory was installed you can update path2py_stubs and you should be good to go.

**Comment by RMCob** [comment]
@bobziroll See Issue #3 for an alternate path to try.

**Comment by bobziroll** [comment]
> @bobziroll See Issue #3 for an alternate path to try.

Found it! Very similar to my path: `/volume1/homebridge/node_modules/homebridge-wyze-robovac/py_helpers` Going to try this now.

Thanks! 🙏

**Comment by bobziroll** [comment]
Kicked the can to the next error:

```
[WyzeRoboVac] error: Command failed: python3 /volume1/homebridge/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py ***@gmail.com ***
Traceback (most recent call last):
  File "/volume1/homebridge/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py", line 4, in <module>
    import wyze_sdk
ModuleNotFoundError: No module named 'wyze_sdk'
```

Do I need to manually run some kind of pip install or something?

**Comment by RMCob** [comment]
Did you install the Python wyze_sdk library per [this](https://github.com/RMCob/homebridge-wyze-robovac#requirements)?
If wyze_sdk is installed it should show up when you run the terminal command "pip3 list"
