### ISSUE TITLE
Missing file after installation of the plugin

### ISSUE THREAD

**Issue by bvelasquez** [RMCob/homebridge-wyze-robovac#11]
**Describe The Bug:**
Receiving the following error after installation:

/opt/homebrew/bin/python3: can't open file '/usr/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py': [Errno 2] No such file or directory

**To Reproduce:**
Installed the plugin. Re-started. Error shows up. No devices listed.

**Expected behavior:**

**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by bvelasquez** [comment]
Found it's because I use NVM to install Node and the installation folder is different than the default. Changed the path in the JSON config to point to the correct location, but now I get this:

```
File "/Users/barryvelasquez/.nvm/versions/node/v16.16.0/lib/node_modules/homebridge-wyze-robovac/py_helpers/getVacuumDeviceList.py", line 4, in <module>
    import wyze_sdk
ModuleNotFoundError: No module named 'wyze_sdk'
```

Wondering now how to install the wyze_sdk to handle the nvm installation. pip install of wyze_sdk didn't do it.

**Comment by RMCob** [comment]
@bvelasquez As I said in the README, I only have experience with Homebridge on RPi so I can't really help you. If you do find a solution to installing wyze_sdk in your environment please report the solution here for others to see. Thanks!
