### ISSUE TITLE
Vac battery being reported as a humidity sensor

### ISSUE THREAD

**Issue by tjb1013** [RMCob/homebridge-wyze-robovac#12]
Any way to tell Homebridge the vac battery is not a humidity sensor?

![vac-battery-sensor](https://user-images.githubusercontent.com/4193674/214859875-30b00d10-d0fe-40b4-b953-b6fd12a8563f.png)

**Comment by RMCob** [comment]
No

**Comment by tjb1013** [comment]
Thanks!
