### ISSUE TITLE
Username / Password invalid 

### ISSUE THREAD

**Issue by tryphoon** [RMCob/homebridge-wyze-robovac#14]
**Describe Your Problem:**
Unable to log in using basic login and password. Other Waze plugin (for lights) works perfectly. Using same pair of credentials. 
Using Hoobs 4, up to date 
**Logs:**

```
2/21/2023, 7:46:04 PMwyzerobovacbridge stopping
2/21/2023, 7:46:10 PMWyze Robovac Bridge starting
2/21/2023, 7:46:13 PMWyze Robovac BridgeLoaded plugin 'homebridge-wyze-robovac'
2/21/2023, 7:46:13 PMWyze Robovac BridgeLoading 2 platforms...
2/21/2023, 7:46:13 PMWyze Robovac BridgeWyzeRoboVacERRORINVALID CONFIGURATION FOR PLUGIN: homebridge-wyze-robovac
2/21/2023, 7:46:13 PMWyze Robovac BridgeWyzeRoboVacERRORname, username and/or password not set. Plugin not started.
2/21/2023, 7:46:13 PMWyze Robovac BridgeBridge is running on port 51846.
```

**Plugin Config:**
{
    "platform": "WyzeRoboVac1",
    "name": "WyzeRoboVac1",
    "username": "USERNAME@gmail.com",
    "password": "PASSWORD",
    "refreshInterval": 30000,
    "path2py_stubs": "/usr/lib/node_modules/homebridge-wyze-robovac/py_helpers"
}

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.2.1
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 16.19.1
* **NPM Version**: 8.19.3
* **Operating System**: Raspbian

**Comment by RMCob** [comment]
@tryphoon You have the platform specified as "WyzeRoboVac1". Where did the 1 come from?
Did you update the config file manually rather than using the Settings button in the Homebridge GUI?
Please remove the 1, try again, and report back. Thanks!

From the README:    {
      "platform": "WyzeRoboVac",
      "name": "WyzeRoboVac",
      "username": "YOUR_EMAIL",
      "password": "YOUR_PASSWORD",
      "mfaCode": "YOUR_2FA_AUTHENTICATION_PIN",
      "statusCheckRefreshInterval": "Refresh Interval for status checks after sweeping starts. Default 30 sec",
      "idleBatteryCheckRefreshInterval": "Refresh Interval for battery checks when idle. Default 1800 seconds (30 min)",
      "busyBatteryCheckRefreshInterval": "Refresh Interval for battery checks when busy or charge level < 100. Default 120 seconds (2 min)",
      "path2py_stubs": "Path to Python helper scripts. Default '/usr/lib/node_modules/homebridge-wyze-robovac/py_helpers'",
      "debugLevel": "Can be 0 (no logging), 1 (log.info), or 2 (log.debug)"
    }

**Comment by RMCob** [comment]
Stale
