### ISSUE TITLE
2FA potential issues?

### ISSUE THREAD

**Issue by carTloyal123** [RMCob/homebridge-wyze-robovac#6]
**Describe Your Problem:**

I do not have a vaccuum from Wyze but I was interested in using this repo as a basis for extending some other Wyze devices to Homekit. Because of that I have a quick question, does each run of the python script not require a new mfa code and why not? If I run scripts standalone I have to enter a new mfa code each time, is this not the case when executing them from typescript?

Also as far as I can tell you do not currently use the provided mfaCode in your implementation, is this correct and intended?

**Comment by RMCob** [comment]
Yes.
