### ISSUE TITLE
Moving Away from Connected Home

### ISSUE THREAD

**Issue by carTloyal123** [RMCob/homebridge-wyze-robovac#7]
Hi @RMCob ,

I was wondering why you decided to start using the python library for Wyze API calls instead of the functionality already present in your Wyze-connected-home repo? Is there a specific reason for not using the existing infrastructure in that repo? Thanks!

**Comment by RMCob** [comment]
I have found that having one plugin that supports multiple different device types causes long term maintenance issues.
I did not write the original wyze-conected-home app. I merely added the capability to control the Wyze outdoor plug (hence the -op suffix) and suddenly my version became the mainstream version. When I decided to write the Wyze robovac plugin it was easier to start from scratch.
